version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencart_web
    ports:
      - "8090:80"
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: opencart_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Konurul2025
      MYSQL_DATABASE: opencart_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: opencart_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Konurul2025 